
services:
  db:
    image: postgres:14.4-alpine
    volumes:
      - ./backend/test/resources/sql/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=${MY_POSTGRES_PASSWORD}
    ports:
      - "5432:5432"


  backend:
    volumes:
      - ./backend/src/resources/oAuth.properties:/app/src/main/resources/oAuth.properties
    build: ./backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    profiles: ["web", "standalone"]
    command: ["--mode=${MODE}"]


  frontend:
    build:
      context: ./frontend/ContactSyncVue
      dockerfile: Dockerfile.dev  # Dockerfile.prod
    ports:
      - "5173:5173" # "8081:80" # later for prod
    depends_on:
      - backend
    profiles: ["web"]