
version: "3.9"
services:
  db:
    image: postgres:14.4-alpine
    volumes:
      - ./backend/test/resources/sql/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=${MY_POSTGRES_PASSWORD}
    ports:
      - "5432:5432"