
version: "3.9"
services:
  db:
    image: postgres:14.4-alpine
    volumes:
      - ./backend/test/resources/sql/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=${MY_POSTGRES_PASSWORD}
    ports:
      - "5432:5432"


  backend:
    volumes:
      - ./backend/src/resources/oAuth.properties:/app/src/main/resources/oAuth.properties
    build: ./backend
    depends_on:
      - db
    environment:
      MODE: web
    ports:
      - "8080:8080"
    profiles: ["web"]



  backend-standalone: # runs without frontend
    volumes:
      - ./backend/src/resources/oAuth.properties:/app/src/main/resources/oAuth.properties
    build: ./backend
    depends_on:
      - db
    environment:
      MODE: standalone
    ports:
      - "8080:8080"
    command: ["--mode=standalone"]
    profiles: ["standalone"]

  frontend:
    build: ./frontend/ContactSyncVue
    ports:
      - "8081:80"
    depends_on:
      - backend